pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/Shubhamj1998/two-tier-flask-app.git'
        BRANCH = 'master'
        IMAGE_NAME = 'shubhamj2024/two-tier-flask-app'
        DEPLOYMENT_FILE = 'k8s' // path to your k8s manifest
        GIT_CREDENTIALS_ID = 'Github'
    }

    stages {
        stage('Checkout GitOps Repo') {
            steps {
                git branch: "${master}",
                    url: "${https://github.com/Shubhamj1998/two-tier-flask-app.git}",
                    credentialsId: "${Github}"
            }
        }

        stage('Update Image Tag in Manifest') {
            steps {
                script {
                    // Get the new tag from a parameter or build metadata
                    def newTag = "${env.BUILD_NUMBER}"

                    // Replace the image tag in the deployment file
                    sh """
                        sed -i 's|image: ${IMAGE_NAME}:.*|image: ${IMAGE_NAME}:${newTag}|' ${DEPLOYMENT_FILE}
                    """
                }
            }
        }

        stage('Commit & Push Changes') {
            steps {
                sh '''
                    git config user.email "jadhavdshubham@gmail.com"
                    git config user.name "shubham jadhav"

                    git add ${DEPLOYMENT_FILE}
                    git commit -m "Update image tag to ${IMAGE_NAME}:${BUILD_NUMBER}"
                    git push origin ${BRANCH}
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Image tag updated. ArgoCD will auto-sync the new manifest.'
        }
        failure {
            echo '❌ Failed to update manifest.'
        }
    }
}
